# Generated by Django 3.2 on 2021-06-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_auto_20210608_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='name_telegram',
            field=models.SlugField(blank=True, max_length=30, null=True, verbose_name='Telegram Username'),
        ),
    ]
