# Generated by Django 3.2 on 2021-05-19 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'Functions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SA', 'Saturday'), ('JA', 'Saturday afternoon'), ('WE', 'Wednesday'), ('FR', 'Friday'), ('SP', 'Special'), ('WP', 'Week of Prayer')], max_length=2)),
                ('description', models.TextField(blank=True, verbose_name='Simple Description')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, verbose_name='Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scales.function', verbose_name='Function')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scales.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Time',
                'verbose_name_plural': 'Program Times',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('code', models.SlugField(blank=True, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('leader', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Leadership')),
            ],
            options={
                'verbose_name': 'Ministry',
                'verbose_name_plural': 'Ministries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='function',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scales.ministry', verbose_name='Ministry'),
        ),
        migrations.AddField(
            model_name='function',
            name='overload',
            field=models.ManyToManyField(to='scales.Function', verbose_name='Overload'),
        ),
        migrations.AddField(
            model_name='function',
            name='people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='People'),
        ),
    ]
