# Generated by Django 3.2 on 2021-06-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='program', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='program',
            name='iscription',
            field=models.BooleanField(default=True, verbose_name='Needs subscription?'),
        ),
        migrations.AddField(
            model_name='program',
            name='presential',
            field=models.BooleanField(default=False, verbose_name='Presential?'),
        ),
        migrations.AddField(
            model_name='program',
            name='room',
            field=models.URLField(blank=True, null=True, verbose_name='Room Link'),
        ),
        migrations.AddField(
            model_name='program',
            name='transmission',
            field=models.URLField(blank=True, null=True, verbose_name='Transmission Link'),
        ),
    ]
