# Generated by Django 3.2 on 2021-05-19 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scales', '0003_auto_20210519_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-date'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterField(
            model_name='function',
            name='overload',
            field=models.ManyToManyField(blank=True, to='scales.Function', verbose_name='Overload'),
        ),
        migrations.AlterField(
            model_name='function',
            name='people',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='People'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='leader',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Leadership'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('SA', 'Sábado'), ('JA', 'Saturday afternoon'), ('WE', 'Quarta-feira'), ('SN', 'Domingo'), ('FR', 'Sexta-feira'), ('SP', 'Special'), ('WP', 'Week of Prayer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='programtime',
            name='person',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='programtime',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
    ]
