# Generated by Django 3.2 on 2021-05-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0004_auto_20210519_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtime',
            options={'ordering': ['program', 'time'], 'verbose_name': 'Program Time', 'verbose_name_plural': 'Program Times'},
        ),
        migrations.AddField(
            model_name='programtime',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='programtime',
            name='lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scales.programtime', verbose_name='Look Up'),
        ),
        migrations.AlterField(
            model_name='programtime',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scales.function', verbose_name='Function'),
        ),
    ]
