# Generated by Django 3.2 on 2021-05-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0005_auto_20210525_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtime',
            options={'ordering': ['program__date', 'program__name', 'time'], 'verbose_name': 'Program Time', 'verbose_name_plural': 'Program Times'},
        ),
        migrations.AlterField(
            model_name='programtime',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scales.function', verbose_name='Function'),
        ),
    ]
