# Generated by Django 3.2 on 2021-05-25 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scales', '0006_auto_20210525_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtime',
            name='confirmmed',
            field=models.ManyToManyField(blank=True, related_name='confirmmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmmed'),
        ),
        migrations.AlterField(
            model_name='programtime',
            name='lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scales.programtime', verbose_name='Same as'),
        ),
        migrations.AlterField(
            model_name='programtime',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Person'),
        ),
    ]
