# Generated by Django 3.2 on 2021-06-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
