# Generated by Django 3.2 on 2021-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtime',
            options={'ordering': ['program__date', 'program__type_name', 'time'], 'verbose_name': 'Program Time', 'verbose_name_plural': 'Program Times'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='name',
        ),
        migrations.AddField(
            model_name='program',
            name='type_name',
            field=models.CharField(choices=[('SA', 'Saturday'), ('JA', 'Saturday afternoon'), ('WE', 'Wednesday'), ('SN', 'Sunday'), ('FR', 'Friday'), ('SP', 'Special'), ('WP', 'Week of Prayer')], default='SA', max_length=2),
        ),
    ]
